### ISSUE TITLE
Improve ergonomics of using this library with Salesforce APIs

### ISSUE THREAD

**Issue by criswit** [sigmavirus24/gobayeux#7]
Hello

I am interested in leveraging this library to implement bayeux protocol as is required for long polling with Salesforce streaming API. I noticed that a recent commit to the extension package mentions fixing subscription to Salesforce, so I am assuming that this is definitely a potential use case of this library. 

I am new to Salesforce and was hoping one of this library's contributors had some sample code they could share with me around how to use this library to subscribe to Salesforce streaming APIs. Any tips/references/guidance you could provide would be awesome. Very much appreciated in advance.

Chris

**Comment by sigmavirus24** [comment]
Hi @criswit that contributor would be @zknill if anyone.

To give you a high-level sketch though, you'll want a library that allows you to authenticate with Salesforce and perhaps create a `http.Client` (or `http.Transport`) that has that authentication. Then you can do use `bayeux.WithHTTPClient` or `bayeux.WithHTTPTransport` and emulate https://github.com/sigmavirus24/gobayeux/blob/8e23f51bba44af3474ddd9b92f6e2cd3265300f0/cmd/testutil/main.go#L57-L90

I'd advise going through the [code examples](https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/api_streaming_code_examples.htm) that salesforce documents here.

Cheers,
Ian

**Comment by criswit** [comment]
Hi @sigmavirus24 @zknill 

Thanks for that info. I have done as mentioned, I have an library that authenticates with Salesforce using [JWT](https://github.com/golang/oauth2/blob/master/oauth2.go#L231) and returns me with a *http.client containing the Authorization header (supposedly). 

I am able to perform a handshake, but when trying to subscribe/connect it throws me a 403 unknown client.
```
DEBU[0000] got client                                   
DEBU[0000] starting                                      at=handshake
DEBU[0001] finishing                                     at=handshake duration=737.014372ms
DEBU[0001] starting long-polling loop                    at=start
DEBU[0001] in polling loop                               at=poll
DEBU[0001] got subscription requests                     at=poll
DEBU[0001] starting                                      at=subscribe
error in bayeux client: "unable to subscribe to channels: 403::Unknown client"

```

I have been able to perform a successful handshake and connection (not using this library) when I've made a POST request to with connect parameters and including the "Authorization: OAuth ..." header in that request. To me, it seems like that is what the extensions package is trying to do - however I am yet unable to understand how I am supposed to use that package when creating the Bayeux client.

I've created two gists with my [main](https://gist.github.com/criswit/491092f7b18d5759ea58eaf5d3e8d524) and [sfdc_auth](https://gist.github.com/criswit/0bce2770cf26f78b7b2dd3fc6406645e) source code, if that is helpful. Mainly I'm unsure how I'm supposed to make use of that "extensions"  package or if it's supposed to be taking care of the putting an Authorization header in the Transport implicitly. Thanks again for the support.

**Comment by sigmavirus24** [comment]
You likely don't need the extension package. I was writing that to use with the test utility command in the repository as I know that I can make a Salesforce developer edition org and test against it provided I can get a token out of `sfdx` etc. I just never got around to that.

I think I remember something around Salesforce setting cookies as well. I wonder if the cookie jar isn't attaching those to the request correctly, perhaps because Salesforce is specifying a `Path` attribute that doesn't match the `cometd` URL. Can you see the Cookie headers/Cookie Jar cookies @criswit ?

**Comment by criswit** [comment]
Hey @sigmavirus24 thanks, I was reading something similar [here](https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/intro_client_specs.htm)  

probably didn't do this right, but i modified the "parse response" portion of your [bayeux_client](https://github.com/sigmavirus24/gobayeux/blob/main/bayeux_client.go#L295) to iterate through the cookies in responses after starting client. here's what i'm seeing

```
DEBU[0000] got client                                   
DEBU[0000] starting                                      at=handshake
DEBU[0001] Cookie Name BrowserId                        
DEBU[0001] Cookie Value SPmVCz_sEeuxHFGPBLGF3w          
DEBU[0001] Cookie Path /                                
DEBU[0001] Cookie Name t                                
DEBU[0001] Cookie Value !0vaFlJER5UsrfIGrfKp9YI2pARkJi5YS8O/yCf8GE+6HiX+CvWWacnC3MzF+OXsuC3USJWIP3jamDQ== 
DEBU[0001] Cookie Path /cometd/                         
DEBU[0001] Cookie Name BAYEUX_BROWSER                   
DEBU[0001] Cookie Value eb4ajzqv8f0j5yiakirz4ui41ah6    
DEBU[0001] Cookie Path /cometd/                         
DEBU[0001] Cookie Name force-stream                     
DEBU[0001] Cookie Value !u+63QcPFhMWL7Ti5ygfhHl1kwJScsjM7XyMnY4Kg2rV5HBLIAYV52ek1x6NWczMA5Uxjyi6PsMtOBlk= 
DEBU[0001] Cookie Path /                                
DEBU[0001] finishing                                     at=handshake duration=360.963931ms
DEBU[0001] starting long-polling loop                    at=start
DEBU[0001] in polling loop                               at=poll
DEBU[0001] got subscription requests                     at=poll
DEBU[0001] starting                                      at=subscribe
DEBU[0001] Cookie Name BrowserId                        
DEBU[0001] Cookie Value SQZmtz_sEeu88MlxpRNA4Q          
DEBU[0001] Cookie Path /                                
DEBU[0001] Cookie Name t                                
DEBU[0001] Cookie Value !0vaFlJER5UsrfIGrfKp9YI2pARkJi5YS8O/yCf8GE+6HiX+CvWWacnC3MzF+OXsuC3USJWIP3jamDQ== 
DEBU[0001] Cookie Path /cometd/                         
DEBU[0001] Cookie Name force-stream                     
DEBU[0001] Cookie Value !H4zwzZfEmdG6M/W5ygfhHl1kwJScsqFUVf+op6XrBcME/iCyxnymkkfXF6ArBvMz0WjyR05+PNO8QaY= 
DEBU[0001] Cookie Path /                                
error in bayeux client: "unable to subscribe to channels: 403::Unknown client"

```

looks like the "force-stream" cookie has a different value, and BAYEUX_BROWSER is present in handshake response but not in subscribe/connect response. am i understanding this correctly? will continue to investigate .

**Comment by criswit** [comment]
i might have got  it...

```
DEBU[0000] got client                                   
DEBU[0000] starting                                      at=handshake
DEBU[0001] Cookie Name BrowserId                        
DEBU[0001] Cookie Value gohQhz_uEeu88MlxpRNA4Q          
DEBU[0001] Cookie Path /                                
DEBU[0001] Cookie Name t                                
DEBU[0001] Cookie Value !0vaFlJER5UsrfIGrfKp9YI2pARkJi5YS8O/yCf8GE+6HiX+CvWWacnC3MzF+OXsuC3USJWIP3jamDQ== 
DEBU[0001] Cookie Path /cometd/                         
DEBU[0001] Cookie Name BAYEUX_BROWSER                   
DEBU[0001] Cookie Value bbdcf6yxjkcn3dzekirzpbto113w    
DEBU[0001] Cookie Path /cometd/                         
DEBU[0001] Cookie Name force-stream                     
DEBU[0001] Cookie Value !pdMAjDyuH2x96F0KdVzjdDX+5Mc4L305KNCPIJWoGUR26RPyHnlHmHW0dgLYO6WuVuXR0EvOCaGapzU= 
DEBU[0001] Cookie Path /                                
DEBU[0001] finishing                                     at=handshake duration=280.789206ms
DEBU[0001] starting long-polling loop                    at=start
DEBU[0001] in polling loop                               at=poll
DEBU[0001] got subscription requests                     at=poll
DEBU[0001] starting                                      at=subscribe
DEBU[0001] finishing                                     at=subscribe duration=143.31755ms
DEBU[0001] queued next /meta/connect request             at=enqueueConnectRequest
DEBU[0001] in polling loop                               at=poll
DEBU[0001] checking for new messages                     at=poll
DEBU[0001] starting                                      at=connect
DEBU[0001] finishing                                     at=connect duration=52.961874ms
DEBU[0001] delivering messages                           at=poll
DEBU[0001] in polling loop                               at=poll
DEBU[0001] queued next /meta/connect request             at=enqueueConnectRequest
DEBU[0001] in polling loop                               at=poll
DEBU[0001] checking for new messages                     at=poll
DEBU[0001] starting                                      at=connect

```

**Comment by sigmavirus24** [comment]
Interesting, what changed? 

Also you probably don't want to be putting cookie values in public issues like this as that's a secret leak technically speaking.

**Comment by sigmavirus24** [comment]
Also @criswit if there's anything you think we should add to help better support Salesforce, I'd be very open to reviewing PRs around this.

**Comment by criswit** [comment]
i'd love to contribute (even if just a little) let me cleanup what i have and circle back to you tomorrow. also - appreciate the security heads up

**Comment by sigmavirus24** [comment]
Looking forward to it @criswit and glad you got things working

**Comment by criswit** [comment]
hey @sigmavirus24 , sorry for the huge delay on this. i finally got around to putting some of my changes in which make this library connect to salesforce. i forked your repo and added the commit there so you can check it out and let me know any thoughts before i actually go about sending you a PR to review.

also - i want to help get the replay functionality included/working in this repo as well. might need a bit of guidance on how we should do that. 

let me know your thoughts on this commit and the effect it might have on your library

https://github.com/criswit/gobayeux/commit/decedc58c8bd8ea8aebbf68295616c593799c9d3

**Comment by sigmavirus24** [comment]
Hi @criswit thanks for pushing that up for us to look at. I've been meaning to comment here and just have been busy. Sorry about that.

So a few things:

1. I think the auth part of this should be handled via the `Transport` I think we could improve https://github.com/sigmavirus24/gobayeux/blob/8e23f51bba44af3474ddd9b92f6e2cd3265300f0/extensions/salesforce/salesforce.go#L9-L44 to cover the gaps you've found. 
   Are you okay with me pulling your commit and updating it to cover what I think needs coverage?

2. For replay IDs does, https://github.com/sigmavirus24/gobayeux/blob/main/extensions/replay/replay.go not work for you? Technically replay IDs are an extension of the Bayeux protocol that Salesforce added to their servers. So it's an optional extension to the library that you'd need to configure. There's an in memory backend there but there's an interface you can implement if you wanted to store IDs in a data store (Redis, Memcached, etc.)

**Comment by criswit** [comment]
@sigmavirus24  hey - thanks for getting back , no worries about delay. quickly to respond to your questions (will circle back with more details on item 2)
1. yes - absolutely ok with this. let me know how i can further help.
2. I think i was able to get replayIds working , but I had to add some extension methods to the SubscribeRequestBuilder (i think) . i will go back to find where i did that and get back to you
let me know any thoughts

**Comment by sigmavirus24** [comment]
@criswit you've got the logic to add cookies to each request but you don't seem to pull them off from anywhere to store them. How is that code helping?

**Comment by sigmavirus24** [comment]
@criswit I updated some things to fix oversights and add documentation. Hopefully that helps

**Comment by criswit** [comment]
thanks @sigmavirus24

**Comment by sigmavirus24** [comment]
@criswit anything else to make this easier to use is also welcome feedback

**Comment by criswit** [comment]
sounds good. will keep in touch @sigmavirus24 . thanks for all your help
